# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py


# Optionally set the version of Python and requirements required to build your docs
# RTD currently doesn't support pipenv (Pipfile) for listing the requirements.
python:
   version: "3.6"
   install:
   - requirements: docs/requirements.txt
