name: Build documentation
on: [push, pull_request]
  # push:
  #   tags:
  #     - 'v*.*.*'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install Sphinx ; pip install m2r2
      - name: Checkout repo
        uses: actions/checkout@v2
      # - name: Get incoming tags
      #   run: echo "{GIT_TAG}={`echo $(git describe --tags --abbrev=0)`}" >> $GITHUB_ENV
      - name: Create a new branch for docs
        run: git checkout --orphan docs/v1.0.0
      - name: Update the docs
        run: |
          cd docs
          make api_docs
      - name: Setup git agent and commit changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/automata-tech/eva_python_sdk
          git config --global user.email "docs@automata.tech"
          git config --global user.name "docs-bot"
          git commit -am 'docs'
          git push origin docs/v1.0.0
      # - name: Commit and push changes
      #   run: |
